import type { Language } from './i18n';
import type { RuneKey } from './runes';

export interface RuneLocalizedText {
  name: string;
  meaning: string;
  symbolism: string;
  keywords: string[];
  divination: string;
}

export type RuneLocalizationTable = Record<RuneKey, RuneLocalizedText>;

// Fallback order: requested → en → ko
export function getRuneLocalization(language: Language, key: RuneKey): RuneLocalizedText {
  const fallbackEnTable = runeLocalizations.en ?? runeLocalizations.ko!;
  const fallbackKoTable = runeLocalizations.ko ?? runeLocalizations.en!;
  const table = runeLocalizations[language] ?? fallbackEnTable;

  const fallbackEn = fallbackEnTable[key];
  const fallbackKo = fallbackKoTable[key];
  return table[key] ?? fallbackEn ?? fallbackKo;
}

export const runeLocalizations: Partial<Record<Language, RuneLocalizationTable>> = {
  ko: {
    fehu: {
      name: '페후 (Fehu)',
      meaning: '"소", "재산", "부"를 의미합니다. 물질적 풍요와 성공을 상징합니다.',
      symbolism: '노동의 결실, 창의력, 새로운 시작을 나타냅니다.',
      keywords: ['재산', '성공', '풍요', '에너지'],
      divination: '물질적 성공과 새로운 기회의 상징',
    },
    uruz: {
      name: '우루즈 (Uruz)',
      meaning: '"야생 황소", "힘", "생명력"을 의미합니다. 원시적 힘과 생명력을 상징합니다.',
      symbolism: '내적 힘, 용기, 자연의 거친 힘을 나타냅니다.',
      keywords: ['힘', '용기', '생명력', '변화'],
      divination: '강한 의지력과 생명력의 발현',
    },
    thurisaz: {
      name: '수리사즈 (Thurisaz)',
      meaning: '"거인", "가시", "토르의 망치"를 의미합니다. 보호와 방어를 상징합니다.',
      symbolism: '적극적 방어, 보호, 강력한 힘을 나타냅니다.',
      keywords: ['보호', '방어', '힘', '도전'],
      divination: '위험으로부터의 보호와 강한 의지',
    },
    ansuz: {
      name: '안수즈 (Ansuz)',
      meaning: '"신", "오딘", "지혜"를 의미합니다. 신적 지혜와 영감을 상징합니다.',
      symbolism: '소통, 지혜, 영감, 신적 메시지를 나타냅니다.',
      keywords: ['지혜', '소통', '영감', '신성'],
      divination: '신적 지혜와 영감의 전달',
    },
    raidho: {
      name: '라이도 (Raidho)',
      meaning: '"여행", "말타기", "이동"을 의미합니다. 여정과 변화를 상징합니다.',
      symbolism: '인생의 여정, 발전, 리듬을 나타냅니다.',
      keywords: ['여행', '변화', '발전', '리듬'],
      divination: '인생의 여정과 올바른 방향',
    },
    kaunan: {
      name: '카오난 (Kaunan)',
      meaning: '"횃불", "빛", "지식"을 의미합니다. 지식과 깨달음을 상징합니다.',
      symbolism: '창조력, 예술, 기술, 변화를 나타냅니다.',
      keywords: ['지식', '창조', '예술', '변화'],
      divination: '창조적 힘과 새로운 지식의 습득',
    },
    gebo: {
      name: '게보 (Gebo)',
      meaning: '"선물", "교환", "균형"을 의미합니다. 상호 교환과 균형을 상징합니다.',
      symbolism: '관계, 파트너십, 균형, 호혜를 나타냅니다.',
      keywords: ['선물', '교환', '균형', '관계'],
      divination: '균형잡힌 관계와 상호 존중',
    },
    wunjo: {
      name: '운요 (Wunjo)',
      meaning: '"기쁨", "행복", "조화"를 의미합니다. 소원 성취와 만족을 상징합니다.',
      symbolism: '내적 평화, 만족, 삶의 균형을 나타냅니다.',
      keywords: ['기쁨', '행복', '조화', '만족'],
      divination: '행복과 내적 평화의 달성',
    },
    hagalaz: {
      name: '하갈라즈 (Hagalaz)',
      meaning: '"우박", "파괴", "시련"을 의미합니다. 시련과 변화를 상징합니다.',
      symbolism: '시련, 파괴적 변화, 새로운 시작을 나타냅니다.',
      keywords: ['시련', '파괴', '변화', '재생'],
      divination: '시련을 통한 성장과 변화',
    },
    nauthiz: {
      name: '나우디즈 (Nauthiz)',
      meaning: '"필요", "궁핍", "제약"을 의미합니다. 필요와 욕구를 상징합니다.',
      symbolism: '인내, 제약, 학습, 성장을 나타냅니다.',
      keywords: ['필요', '인내', '제약', '학습'],
      divination: '인내를 통한 성장과 지혜',
    },
    isaz: {
      name: '이사즈 (Isaz)',
      meaning: '"얼음", "정체", "집중"을 의미합니다. 집중과 명상을 상징합니다.',
      symbolism: '집중, 명상, 내적 성찰을 나타냅니다.',
      keywords: ['얼음', '집중', '명상', '정체'],
      divination: '내적 성찰과 집중의 필요성',
    },
    jera: {
      name: '예라 (Jera)',
      meaning: '"해", "풍년", "수확"을 의미합니다. 좋은 결과를 얻기 위한 노력과 인내를 상징합니다.',
      symbolism: '농업과 계절의 순환, 자연의 리듬에 맞춘 삶을 나타냅니다.',
      keywords: ['수확', '노력', '인내', '결실'],
      divination: '노력의 결실과 자연스러운 순환',
    },
    eihwaz: {
      name: '에이와즈 (Eihwaz)',
      meaning: '"주목나무", "죽음과 재생", "변화"를 의미합니다. 변화와 재생을 상징합니다.',
      symbolism: '변화, 재생, 영적 성장을 나타냅니다.',
      keywords: ['변화', '재생', '성장', '영성'],
      divination: '변화를 통한 영적 성장',
    },
    perthro: {
      name: '페르스로 (Perthro)',
      meaning: '"운명", "신비", "숨겨진 것"을 의미합니다. 운명과 비밀을 상징합니다.',
      symbolism: '운명, 비밀, 숨겨진 지식을 나타냅니다.',
      keywords: ['운명', '비밀', '신비', '지식'],
      divination: '숨겨진 지식과 운명의 힘',
    },
    algiz: {
      name: '알기즈 (Algiz)',
      meaning: '"방어", "보호", "연결"을 의미합니다. 신적 보호와 연결을 상징합니다.',
      symbolism: '보호, 신적 연결, 영적 각성을 나타냅니다.',
      keywords: ['보호', '연결', '각성', '신성'],
      divination: '신적 보호와 영적 각성',
    },
    sowilo: {
      name: '소윌로 (Sowilo)',
      meaning: '"태양", "승리", "성공"을 의미합니다. 성공과 승리를 상징합니다.',
      symbolism: '성공, 승리, 생명력, 빛을 나타냅니다.',
      keywords: ['태양', '승리', '성공', '생명력'],
      divination: '성공과 승리의 확신',
    },
    tiwaz: {
      name: '티와즈 (Tiwaz)',
      meaning: '"티르 신", "전쟁", "정의"를 의미합니다. 정의와 희생을 상징합니다.',
      symbolism: '정의, 희생, 용기, 리더십을 나타냅니다.',
      keywords: ['정의', '희생', '용기', '리더십'],
      divination: '정의로운 희생과 용기',
    },
    berkanan: {
      name: '베르카난 (Berkanan)',
      meaning: '"자작나무", "성장", "새로운 시작"을 의미합니다. 성장과 재생을 상징합니다.',
      symbolism: '성장, 재생, 여성성, 출산을 나타냅니다.',
      keywords: ['성장', '재생', '새로운 시작', '여성성'],
      divination: '새로운 시작과 성장의 기회',
    },
    ehwaz: {
      name: '에와즈 (Ehwaz)',
      meaning: '"말", "파트너십", "신뢰"를 의미합니다. 신뢰와 협력을 상징합니다.',
      symbolism: '파트너십, 신뢰, 협력, 충성을 나타냅니다.',
      keywords: ['파트너십', '신뢰', '협력', '충성'],
      divination: '신뢰할 수 있는 파트너십',
    },
    mannaz: {
      name: '만나즈 (Mannaz)',
      meaning: '"인간", "공동체", "상호 의존"을 의미합니다. 인간성과 공동체를 상징합니다.',
      symbolism: '인간성, 공동체, 상호 의존, 지혜를 나타냅니다.',
      keywords: ['인간', '공동체', '지혜', '상호의존'],
      divination: '인간적 지혜와 공동체 정신',
    },
    laguz: {
      name: '라구즈 (Laguz)',
      meaning: '"물", "흐름", "직관"을 의미합니다. 직관과 감정을 상징합니다.',
      symbolism: '직관, 감정, 흐름, 변화를 나타냅니다.',
      keywords: ['물', '직관', '감정', '흐름'],
      divination: '직관을 따르는 것의 중요성',
    },
    ingwaz: {
      name: '잉와즈 (Ingwaz)',
      meaning: '"잉 신", "풍요", "완성"을 의미합니다. 완성과 풍요를 상징합니다.',
      symbolism: '완성, 풍요, 내적 성장을 나타냅니다.',
      keywords: ['완성', '풍요', '성장', '내적 힘'],
      divination: '내적 성장과 완성의 단계',
    },
    dagaz: {
      name: '다가즈 (Dagaz)',
      meaning: '"낮", "각성", "깨달음"을 의미합니다. 깨달음과 변화를 상징합니다.',
      symbolism: '깨달음, 각성, 균형, 변화를 나타냅니다.',
      keywords: ['깨달음', '각성', '균형', '변화'],
      divination: '깨달음과 새로운 인식의 시작',
    },
    othalan: {
      name: '오달란 (Othalan)',
      meaning: '"유산", "조상의 땅", "상속받은 재산"을 의미합니다. 가족과 전통, 뿌리를 상징합니다.',
      symbolism: '가문의 명예와 전통, 조상으로부터 물려받은 지혜를 나타냅니다.',
      keywords: ['유산', '전통', '가족', '뿌리'],
      divination: '가족의 전통과 조상의 지혜',
    },
  },

  en: {
    fehu: {
      name: 'Fehu',
      meaning: 'Means "cattle", "wealth", and "property". It symbolizes material abundance and success.',
      symbolism: 'Represents the fruits of labor, creativity, and new beginnings.',
      keywords: ['wealth', 'success', 'abundance', 'energy'],
      divination: 'A sign of material success and new opportunities.',
    },
    uruz: {
      name: 'Uruz',
      meaning: 'Means "wild ox", "strength", and "vitality". It symbolizes primal power and life force.',
      symbolism: 'Represents inner strength, courage, and the raw power of nature.',
      keywords: ['strength', 'courage', 'vitality', 'change'],
      divination: 'The emergence of strong willpower and vitality.',
    },
    thurisaz: {
      name: 'Thurisaz',
      meaning: 'Means "giant", "thorn", and "Thor\'s hammer". It symbolizes protection and defense.',
      symbolism: 'Represents active defense, protection, and formidable power.',
      keywords: ['protection', 'defense', 'power', 'challenge'],
      divination: 'Protection from danger and unwavering determination.',
    },
    ansuz: {
      name: 'Ansuz',
      meaning: 'Means "god", "Odin", and "wisdom". It symbolizes divine wisdom and inspiration.',
      symbolism: 'Represents communication, wisdom, inspiration, and sacred messages.',
      keywords: ['wisdom', 'communication', 'inspiration', 'sacred'],
      divination: 'A channel for divine wisdom and inspiration.',
    },
    raidho: {
      name: 'Raidho',
      meaning: 'Means "journey", "riding", and "movement". It symbolizes travel and change.',
      symbolism: 'Represents life\'s journey, growth, and rhythm.',
      keywords: ['journey', 'change', 'growth', 'rhythm'],
      divination: 'The right path and direction on your journey.',
    },
    kaunan: {
      name: 'Kaunan',
      meaning: 'Means "torch", "light", and "knowledge". It symbolizes learning and awakening.',
      symbolism: 'Represents creative power, art, skill, and transformation.',
      keywords: ['knowledge', 'creation', 'art', 'change'],
      divination: 'Creative force and the gaining of new knowledge.',
    },
    gebo: {
      name: 'Gebo',
      meaning: 'Means "gift", "exchange", and "balance". It symbolizes reciprocity and harmony.',
      symbolism: 'Represents relationships, partnership, balance, and mutual benefit.',
      keywords: ['gift', 'exchange', 'balance', 'relationship'],
      divination: 'Mutual respect and a balanced relationship.',
    },
    wunjo: {
      name: 'Wunjo',
      meaning: 'Means "joy", "happiness", and "harmony". It symbolizes fulfillment and satisfaction.',
      symbolism: 'Represents inner peace, contentment, and balance in life.',
      keywords: ['joy', 'happiness', 'harmony', 'contentment'],
      divination: 'Achieving happiness and inner peace.',
    },
    hagalaz: {
      name: 'Hagalaz',
      meaning: 'Means "hail", "destruction", and "trial". It symbolizes hardship and transformation.',
      symbolism: 'Represents trials, disruptive change, and fresh beginnings.',
      keywords: ['trial', 'disruption', 'change', 'renewal'],
      divination: 'Growth through hardship and transformation.',
    },
    nauthiz: {
      name: 'Nauthiz',
      meaning: 'Means "need", "scarcity", and "constraint". It symbolizes necessity and desire.',
      symbolism: 'Represents endurance, limitations, learning, and growth.',
      keywords: ['need', 'endurance', 'constraint', 'learning'],
      divination: 'Wisdom gained through patience and endurance.',
    },
    isaz: {
      name: 'Isaz',
      meaning: 'Means "ice", "stillness", and "focus". It symbolizes concentration and meditation.',
      symbolism: 'Represents focus, contemplation, and inner reflection.',
      keywords: ['ice', 'focus', 'meditation', 'stillness'],
      divination: 'A need for focus and inner reflection.',
    },
    jera: {
      name: 'Jera',
      meaning: 'Means "year", "harvest", and "reward". It symbolizes effort and patience for good outcomes.',
      symbolism: 'Represents seasonal cycles and living in rhythm with nature.',
      keywords: ['harvest', 'effort', 'patience', 'reward'],
      divination: 'Natural cycles and the fruits of your efforts.',
    },
    eihwaz: {
      name: 'Eihwaz',
      meaning: 'Means "yew tree", "death and rebirth", and "change". It symbolizes transformation and renewal.',
      symbolism: 'Represents change, renewal, and spiritual growth.',
      keywords: ['change', 'rebirth', 'growth', 'spirituality'],
      divination: 'Spiritual growth through transformation.',
    },
    perthro: {
      name: 'Perthro',
      meaning: 'Means "fate", "mystery", and "the hidden". It symbolizes destiny and secrets.',
      symbolism: 'Represents fate, secrets, and hidden knowledge.',
      keywords: ['fate', 'secret', 'mystery', 'knowledge'],
      divination: 'Hidden knowledge and the power of destiny.',
    },
    algiz: {
      name: 'Algiz',
      meaning: 'Means "defense", "protection", and "connection". It symbolizes divine protection.',
      symbolism: 'Represents protection, sacred connection, and spiritual awakening.',
      keywords: ['protection', 'connection', 'awakening', 'sacred'],
      divination: 'Divine protection and spiritual awakening.',
    },
    sowilo: {
      name: 'Sowilo',
      meaning: 'Means "sun", "victory", and "success". It symbolizes achievement and triumph.',
      symbolism: 'Represents success, victory, vitality, and light.',
      keywords: ['sun', 'victory', 'success', 'vitality'],
      divination: 'Confidence in success and victory.',
    },
    tiwaz: {
      name: 'Tiwaz',
      meaning: 'Means "the god Tyr", "war", and "justice". It symbolizes justice and sacrifice.',
      symbolism: 'Represents justice, sacrifice, courage, and leadership.',
      keywords: ['justice', 'sacrifice', 'courage', 'leadership'],
      divination: 'Courage and righteous sacrifice.',
    },
    berkanan: {
      name: 'Berkanan',
      meaning: 'Means "birch", "growth", and "new beginnings". It symbolizes renewal and development.',
      symbolism: 'Represents growth, rebirth, femininity, and birth.',
      keywords: ['growth', 'rebirth', 'new beginnings', 'fertility'],
      divination: 'A chance for new beginnings and growth.',
    },
    ehwaz: {
      name: 'Ehwaz',
      meaning: 'Means "horse", "partnership", and "trust". It symbolizes cooperation and loyalty.',
      symbolism: 'Represents partnership, trust, cooperation, and loyalty.',
      keywords: ['partnership', 'trust', 'cooperation', 'loyalty'],
      divination: 'A dependable partnership built on trust.',
    },
    mannaz: {
      name: 'Mannaz',
      meaning: 'Means "human", "community", and "interdependence". It symbolizes humanity and society.',
      symbolism: 'Represents humanity, community, interdependence, and wisdom.',
      keywords: ['humanity', 'community', 'wisdom', 'interdependence'],
      divination: 'Human wisdom and a strong community spirit.',
    },
    laguz: {
      name: 'Laguz',
      meaning: 'Means "water", "flow", and "intuition". It symbolizes intuition and emotion.',
      symbolism: 'Represents intuition, emotion, flow, and change.',
      keywords: ['water', 'intuition', 'emotion', 'flow'],
      divination: 'The importance of following your intuition.',
    },
    ingwaz: {
      name: 'Ingwaz',
      meaning: 'Means "the god Ing", "fertility", and "completion". It symbolizes fulfillment and abundance.',
      symbolism: 'Represents completion, prosperity, and inner growth.',
      keywords: ['completion', 'prosperity', 'growth', 'inner strength'],
      divination: 'A phase of completion and inner maturation.',
    },
    dagaz: {
      name: 'Dagaz',
      meaning: 'Means "day", "awakening", and "insight". It symbolizes realization and change.',
      symbolism: 'Represents insight, awakening, balance, and transformation.',
      keywords: ['insight', 'awakening', 'balance', 'change'],
      divination: 'A new beginning of awareness and perspective.',
    },
    othalan: {
      name: 'Othalan',
      meaning: 'Means "inheritance", "ancestral land", and "legacy". It symbolizes family roots and tradition.',
      symbolism: 'Represents lineage, tradition, and wisdom passed down from ancestors.',
      keywords: ['inheritance', 'tradition', 'family', 'roots'],
      divination: 'Ancestral wisdom and family tradition.',
    },
  },

  ja: {
    fehu: {
      name: 'フェフ (Fehu)',
      meaning: '「家畜」「財産」「富」を意味し、物質的な豊かさと成功を象徴します。',
      symbolism: '努力の結実、創造性、新しい始まりを表します。',
      keywords: ['富', '成功', '豊かさ', 'エネルギー'],
      divination: '物質的成功と新たな機会の兆し',
    },
    uruz: {
      name: 'ウルズ (Uruz)',
      meaning: '「野生の牡牛」「力」「生命力」を意味し、原初の力と活力を象徴します。',
      symbolism: '内なる力、勇気、自然の荒々しい力を表します。',
      keywords: ['力', '勇気', '生命力', '変化'],
      divination: '強い意志と生命力の発現',
    },
    thurisaz: {
      name: 'スリサズ (Thurisaz)',
      meaning: '「巨人」「棘」「トールの槌」を意味し、防護と防衛を象徴します。',
      symbolism: '積極的な防衛、守護、強大な力を表します。',
      keywords: ['守護', '防衛', '力', '挑戦'],
      divination: '危険からの守りと強い決意',
    },
    ansuz: {
      name: 'アンスズ (Ansuz)',
      meaning: '「神」「オーディン」「知恵」を意味し、神聖な知恵と霊感を象徴します。',
      symbolism: 'コミュニケーション、知恵、霊感、神聖なメッセージを表します。',
      keywords: ['知恵', 'コミュニケーション', '霊感', '神聖'],
      divination: '神聖な知恵と霊感の伝達',
    },
    raidho: {
      name: 'ライゾ (Raidho)',
      meaning: '「旅」「騎行」「移動」を意味し、道のりと変化を象徴します。',
      symbolism: '人生の旅、進展、リズムを表します。',
      keywords: ['旅', '変化', '進展', 'リズム'],
      divination: '人生の道のりと正しい方向性',
    },
    kaunan: {
      name: 'カウナン (Kaunan)',
      meaning: '「松明」「光」「知識」を意味し、学びと気づきを象徴します。',
      symbolism: '創造力、芸術、技術、変容を表します。',
      keywords: ['知識', '創造', '芸術', '変化'],
      divination: '創造的な力と新しい知識の獲得',
    },
    gebo: {
      name: 'ゲボ (Gebo)',
      meaning: '「贈り物」「交換」「均衡」を意味し、相互性と調和を象徴します。',
      symbolism: '関係、パートナーシップ、バランス、互恵を表します。',
      keywords: ['贈り物', '交換', '均衡', '関係'],
      divination: 'バランスの取れた関係と相互尊重',
    },
    wunjo: {
      name: 'ウンヨ (Wunjo)',
      meaning: '「喜び」「幸福」「調和」を意味し、成就と満足を象徴します。',
      symbolism: '内なる平和、満足、生活のバランスを表します。',
      keywords: ['喜び', '幸福', '調和', '満足'],
      divination: '幸福と内なる平和の達成',
    },
    hagalaz: {
      name: 'ハガラズ (Hagalaz)',
      meaning: '「雹」「破壊」「試練」を意味し、試練と変化を象徴します。',
      symbolism: '試練、破壊的な変化、新たな始まりを表します。',
      keywords: ['試練', '破壊', '変化', '再生'],
      divination: '試練を通じた成長と変容',
    },
    nauthiz: {
      name: 'ナウシズ (Nauthiz)',
      meaning: '「必要」「欠乏」「制約」を意味し、必要性と欲求を象徴します。',
      symbolism: '忍耐、制限、学び、成長を表します。',
      keywords: ['必要', '忍耐', '制約', '学習'],
      divination: '忍耐によって得られる成長と知恵',
    },
    isaz: {
      name: 'イーサズ (Isaz)',
      meaning: '「氷」「停滞」「集中」を意味し、集中と瞑想を象徴します。',
      symbolism: '集中、瞑想、内省を表します。',
      keywords: ['氷', '集中', '瞑想', '停滞'],
      divination: '内省と集中の必要性',
    },
    jera: {
      name: 'イェラ (Jera)',
      meaning: '「年」「豊作」「収穫」を意味し、良い結果のための努力と忍耐を象徴します。',
      symbolism: '農耕と季節の循環、自然のリズムに合わせた生き方を表します。',
      keywords: ['収穫', '努力', '忍耐', '結実'],
      divination: '努力の実りと自然な循環',
    },
    eihwaz: {
      name: 'エイワズ (Eihwaz)',
      meaning: '「イチイの木」「死と再生」「変化」を意味し、変容と再生を象徴します。',
      symbolism: '変化、再生、霊的成長を表します。',
      keywords: ['変化', '再生', '成長', '霊性'],
      divination: '変化を通じた霊的成長',
    },
    perthro: {
      name: 'ペルスロ (Perthro)',
      meaning: '「運命」「神秘」「隠されたもの」を意味し、運命と秘密を象徴します。',
      symbolism: '運命、秘密、隠された知識を表します。',
      keywords: ['運命', '秘密', '神秘', '知識'],
      divination: '隠された知識と運命の力',
    },
    algiz: {
      name: 'アルギズ (Algiz)',
      meaning: '「防衛」「守護」「つながり」を意味し、神聖な守護と結びつきを象徴します。',
      symbolism: '守護、神聖なつながり、霊的覚醒を表します。',
      keywords: ['守護', 'つながり', '覚醒', '神聖'],
      divination: '神聖な守護と霊的覚醒',
    },
    sowilo: {
      name: 'ソウィロ (Sowilo)',
      meaning: '「太陽」「勝利」「成功」を意味し、成功と勝利を象徴します。',
      symbolism: '成功、勝利、生命力、光を表します。',
      keywords: ['太陽', '勝利', '成功', '生命力'],
      divination: '成功と勝利への確信',
    },
    tiwaz: {
      name: 'ティワズ (Tiwaz)',
      meaning: '「軍神テュール」「戦い」「正義」を意味し、正義と犠牲を象徴します。',
      symbolism: '正義、犠牲、勇気、リーダーシップを表します。',
      keywords: ['正義', '犠牲', '勇気', 'リーダーシップ'],
      divination: '正義のための犠牲と勇気',
    },
    berkanan: {
      name: 'ベルカナン (Berkanan)',
      meaning: '「白樺」「成長」「新しい始まり」を意味し、成長と再生を象徴します。',
      symbolism: '成長、再生、女性性、誕生を表します。',
      keywords: ['成長', '再生', '新しい始まり', '女性性'],
      divination: '新たな始まりと成長の機会',
    },
    ehwaz: {
      name: 'エワズ (Ehwaz)',
      meaning: '「馬」「パートナーシップ」「信頼」を意味し、信頼と協力を象徴します。',
      symbolism: 'パートナーシップ、信頼、協力、忠誠を表します。',
      keywords: ['パートナーシップ', '信頼', '協力', '忠誠'],
      divination: '信頼できるパートナーシップ',
    },
    mannaz: {
      name: 'マンナズ (Mannaz)',
      meaning: '「人間」「共同体」「相互依存」を意味し、人間性と社会を象徴します。',
      symbolism: '人間性、共同体、相互依存、知恵を表します。',
      keywords: ['人間', '共同体', '知恵', '相互依存'],
      divination: '人間的な知恵と共同体精神',
    },
    laguz: {
      name: 'ラグズ (Laguz)',
      meaning: '「水」「流れ」「直感」を意味し、直感と感情を象徴します。',
      symbolism: '直感、感情、流れ、変化を表します。',
      keywords: ['水', '直感', '感情', '流れ'],
      divination: '直感に従うことの重要性',
    },
    ingwaz: {
      name: 'イングワズ (Ingwaz)',
      meaning: '「神イング」「豊穣」「完成」を意味し、完成と豊かさを象徴します。',
      symbolism: '完成、豊かさ、内的成長を表します。',
      keywords: ['完成', '豊かさ', '成長', '内なる力'],
      divination: '内的成長と完成の段階',
    },
    dagaz: {
      name: 'ダガズ (Dagaz)',
      meaning: '「昼」「覚醒」「悟り」を意味し、気づきと変化を象徴します。',
      symbolism: '悟り、覚醒、均衡、変化を表します。',
      keywords: ['悟り', '覚醒', '均衡', '変化'],
      divination: '気づきと新しい認識の始まり',
    },
    othalan: {
      name: 'オーダラン (Othalan)',
      meaning: '「遺産」「祖先の土地」「受け継いだ財産」を意味し、家族と伝統、ルーツを象徴します。',
      symbolism: '家系の名誉と伝統、祖先から受け継いだ知恵を表します。',
      keywords: ['遺産', '伝統', '家族', 'ルーツ'],
      divination: '家族の伝統と祖先の知恵',
    },
  },

  zh: {
    fehu: {
      name: '费胡 (Fehu)',
      meaning: '意为“牛”“财富”“财产”，象征物质丰盛与成功。',
      symbolism: '代表劳动的成果、创造力与新的开始。',
      keywords: ['财富', '成功', '丰盛', '能量'],
      divination: '物质成功与新机会的象征',
    },
    uruz: {
      name: '乌鲁兹 (Uruz)',
      meaning: '意为“野牛”“力量”“生命力”，象征原始力量与活力。',
      symbolism: '代表内在力量、勇气与自然的粗犷之力。',
      keywords: ['力量', '勇气', '生命力', '变化'],
      divination: '强烈意志与生命力的显现',
    },
    thurisaz: {
      name: '苏里萨兹 (Thurisaz)',
      meaning: '意为“巨人”“荆棘”“雷神之锤”，象征保护与防御。',
      symbolism: '代表主动防御、守护与强大的力量。',
      keywords: ['保护', '防御', '力量', '挑战'],
      divination: '免于危险的守护与坚定意志',
    },
    ansuz: {
      name: '安苏兹 (Ansuz)',
      meaning: '意为“神”“奥丁”“智慧”，象征神圣智慧与灵感。',
      symbolism: '代表沟通、智慧、灵感与神圣讯息。',
      keywords: ['智慧', '沟通', '灵感', '神圣'],
      divination: '传递神圣智慧与灵感',
    },
    raidho: {
      name: '莱兹霍 (Raidho)',
      meaning: '意为“旅程”“骑行”“移动”，象征道路与变化。',
      symbolism: '代表人生的旅程、发展与节奏。',
      keywords: ['旅程', '变化', '发展', '节奏'],
      divination: '人生旅途与正确方向',
    },
    kaunan: {
      name: '考南 (Kaunan)',
      meaning: '意为“火炬”“光”“知识”，象征知识与觉悟。',
      symbolism: '代表创造力、艺术、技艺与转变。',
      keywords: ['知识', '创造', '艺术', '变化'],
      divination: '创造之力与获取新知识',
    },
    gebo: {
      name: '盖博 (Gebo)',
      meaning: '意为“礼物”“交换”“平衡”，象征互惠与均衡。',
      symbolism: '代表关系、伙伴、平衡与互利。',
      keywords: ['礼物', '交换', '平衡', '关系'],
      divination: '平衡的关系与相互尊重',
    },
    wunjo: {
      name: '温约 (Wunjo)',
      meaning: '意为“喜悦”“幸福”“和谐”，象征满足与圆满。',
      symbolism: '代表内在平和、满足与生活的平衡。',
      keywords: ['喜悦', '幸福', '和谐', '满足'],
      divination: '达成幸福与内在安宁',
    },
    hagalaz: {
      name: '哈加拉兹 (Hagalaz)',
      meaning: '意为“冰雹”“破坏”“考验”，象征试炼与改变。',
      symbolism: '代表试炼、冲击性的变化与新的开始。',
      keywords: ['试炼', '破坏', '变化', '再生'],
      divination: '通过考验获得成长与转变',
    },
    nauthiz: {
      name: '瑙西兹 (Nauthiz)',
      meaning: '意为“需要”“匮乏”“限制”，象征需求与欲望。',
      symbolism: '代表忍耐、限制、学习与成长。',
      keywords: ['需要', '忍耐', '限制', '学习'],
      divination: '以忍耐换取成长与智慧',
    },
    isaz: {
      name: '伊萨兹 (Isaz)',
      meaning: '意为“冰”“停滞”“专注”，象征专注与冥想。',
      symbolism: '代表专注、沉思与内在省察。',
      keywords: ['冰', '专注', '冥想', '停滞'],
      divination: '需要专注与内在反思',
    },
    jera: {
      name: '耶拉 (Jera)',
      meaning: '意为“年”“丰收”“收获”，象征为好结果而付出的努力与耐心。',
      symbolism: '代表农业与季节循环，以及与自然节奏同步的生活。',
      keywords: ['收获', '努力', '耐心', '成果'],
      divination: '努力的成果与自然的循环',
    },
    eihwaz: {
      name: '艾瓦兹 (Eihwaz)',
      meaning: '意为“紫杉”“死亡与重生”“变化”，象征转化与再生。',
      symbolism: '代表变化、再生与灵性成长。',
      keywords: ['变化', '再生', '成长', '灵性'],
      divination: '通过转化实现灵性成长',
    },
    perthro: {
      name: '佩尔斯罗 (Perthro)',
      meaning: '意为“命运”“神秘”“隐藏之物”，象征命运与秘密。',
      symbolism: '代表命运、秘密与隐藏的知识。',
      keywords: ['命运', '秘密', '神秘', '知识'],
      divination: '隐藏知识与命运之力',
    },
    algiz: {
      name: '阿尔吉兹 (Algiz)',
      meaning: '意为“防御”“保护”“连接”，象征神圣守护与连接。',
      symbolism: '代表保护、神圣连接与灵性觉醒。',
      keywords: ['保护', '连接', '觉醒', '神圣'],
      divination: '神圣守护与灵性觉醒',
    },
    sowilo: {
      name: '索维洛 (Sowilo)',
      meaning: '意为“太阳”“胜利”“成功”，象征成功与凯旋。',
      symbolism: '代表成功、胜利、生命力与光明。',
      keywords: ['太阳', '胜利', '成功', '生命力'],
      divination: '对成功与胜利的确信',
    },
    tiwaz: {
      name: '提瓦兹 (Tiwaz)',
      meaning: '意为“提尔神”“战争”“正义”，象征正义与牺牲。',
      symbolism: '代表正义、牺牲、勇气与领导力。',
      keywords: ['正义', '牺牲', '勇气', '领导力'],
      divination: '为正义而战的勇气与牺牲',
    },
    berkanan: {
      name: '贝尔卡南 (Berkanan)',
      meaning: '意为“桦树”“成长”“新开始”，象征成长与再生。',
      symbolism: '代表成长、再生、女性力量与诞生。',
      keywords: ['成长', '再生', '新开始', '女性力量'],
      divination: '新的开始与成长的机会',
    },
    ehwaz: {
      name: '埃瓦兹 (Ehwaz)',
      meaning: '意为“马”“伙伴关系”“信任”，象征信任与协作。',
      symbolism: '代表伙伴关系、信任、协作与忠诚。',
      keywords: ['伙伴关系', '信任', '协作', '忠诚'],
      divination: '值得信赖的伙伴关系',
    },
    mannaz: {
      name: '曼纳兹 (Mannaz)',
      meaning: '意为“人类”“共同体”“相互依存”，象征人性与社会。',
      symbolism: '代表人性、共同体、相互依存与智慧。',
      keywords: ['人类', '共同体', '智慧', '相互依存'],
      divination: '人类智慧与共同体精神',
    },
    laguz: {
      name: '拉古兹 (Laguz)',
      meaning: '意为“水”“流动”“直觉”，象征直觉与情感。',
      symbolism: '代表直觉、情感、流动与变化。',
      keywords: ['水', '直觉', '情感', '流动'],
      divination: '遵循直觉的重要性',
    },
    ingwaz: {
      name: '因格瓦兹 (Ingwaz)',
      meaning: '意为“因格神”“丰饶”“完成”，象征圆满与丰盛。',
      symbolism: '代表完成、丰盛与内在成长。',
      keywords: ['完成', '丰盛', '成长', '内在力量'],
      divination: '内在成长与完成的阶段',
    },
    dagaz: {
      name: '达加兹 (Dagaz)',
      meaning: '意为“白昼”“觉醒”“领悟”，象征觉悟与变化。',
      symbolism: '代表领悟、觉醒、平衡与转化。',
      keywords: ['领悟', '觉醒', '平衡', '变化'],
      divination: '觉醒与新认知的开始',
    },
    othalan: {
      name: '欧达兰 (Othalan)',
      meaning: '意为“遗产”“祖先之地”“传承财产”，象征家庭、传统与根基。',
      symbolism: '代表家族荣誉与传统，以及祖先传下的智慧。',
      keywords: ['遗产', '传统', '家庭', '根基'],
      divination: '家族传统与祖先智慧',
    },
  },

  es: {
    fehu: {
      name: 'Fehu',
      meaning: 'Significa "ganado", "riqueza" y "propiedad". Simboliza abundancia material y éxito.',
      symbolism: 'Representa los frutos del esfuerzo, la creatividad y los nuevos comienzos.',
      keywords: ['riqueza', 'éxito', 'abundancia', 'energía'],
      divination: 'Señal de éxito material y nuevas oportunidades.',
    },
    uruz: {
      name: 'Uruz',
      meaning: 'Significa "buey salvaje", "fuerza" y "vitalidad". Simboliza poder primordial y energía vital.',
      symbolism: 'Representa fuerza interior, valentía y el poder crudo de la naturaleza.',
      keywords: ['fuerza', 'valentía', 'vitalidad', 'cambio'],
      divination: 'Manifestación de gran voluntad y vitalidad.',
    },
    thurisaz: {
      name: 'Thurisaz',
      meaning: 'Significa "gigante", "espina" y "martillo de Thor". Simboliza protección y defensa.',
      symbolism: 'Representa defensa activa, protección y poder formidable.',
      keywords: ['protección', 'defensa', 'poder', 'desafío'],
      divination: 'Protección ante el peligro y determinación firme.',
    },
    ansuz: {
      name: 'Ansuz',
      meaning: 'Significa "dios", "Odín" y "sabiduría". Simboliza sabiduría divina e inspiración.',
      symbolism: 'Representa comunicación, sabiduría, inspiración y mensajes sagrados.',
      keywords: ['sabiduría', 'comunicación', 'inspiración', 'sagrado'],
      divination: 'Transmisión de sabiduría e inspiración divina.',
    },
    raidho: {
      name: 'Raidho',
      meaning: 'Significa "viaje", "cabalgata" y "movimiento". Simboliza el camino y el cambio.',
      symbolism: 'Representa el viaje de la vida, el progreso y el ritmo.',
      keywords: ['viaje', 'cambio', 'progreso', 'ritmo'],
      divination: 'Dirección correcta y camino adecuado.',
    },
    kaunan: {
      name: 'Kaunan',
      meaning: 'Significa "antorcha", "luz" y "conocimiento". Simboliza aprendizaje y revelación.',
      symbolism: 'Representa creatividad, arte, habilidad y transformación.',
      keywords: ['conocimiento', 'creación', 'arte', 'cambio'],
      divination: 'Fuerza creativa y adquisición de nuevo conocimiento.',
    },
    gebo: {
      name: 'Gebo',
      meaning: 'Significa "regalo", "intercambio" y "equilibrio". Simboliza reciprocidad y armonía.',
      symbolism: 'Representa relaciones, asociación, equilibrio y beneficio mutuo.',
      keywords: ['regalo', 'intercambio', 'equilibrio', 'relación'],
      divination: 'Relación equilibrada y respeto mutuo.',
    },
    wunjo: {
      name: 'Wunjo',
      meaning: 'Significa "alegría", "felicidad" y "armonía". Simboliza plenitud y satisfacción.',
      symbolism: 'Representa paz interior, satisfacción y equilibrio en la vida.',
      keywords: ['alegría', 'felicidad', 'armonía', 'satisfacción'],
      divination: 'Logro de felicidad y paz interior.',
    },
    hagalaz: {
      name: 'Hagalaz',
      meaning: 'Significa "granizo", "destrucción" y "prueba". Simboliza adversidad y transformación.',
      symbolism: 'Representa pruebas, cambios disruptivos y nuevos comienzos.',
      keywords: ['prueba', 'destrucción', 'cambio', 'renovación'],
      divination: 'Crecimiento a través de la adversidad y el cambio.',
    },
    nauthiz: {
      name: 'Nauthiz',
      meaning: 'Significa "necesidad", "carencia" y "limitación". Simboliza necesidad y deseo.',
      symbolism: 'Representa paciencia, restricciones, aprendizaje y crecimiento.',
      keywords: ['necesidad', 'paciencia', 'limitación', 'aprendizaje'],
      divination: 'Sabiduría obtenida mediante paciencia y resistencia.',
    },
    isaz: {
      name: 'Isaz',
      meaning: 'Significa "hielo", "estancamiento" y "enfoque". Simboliza concentración y meditación.',
      symbolism: 'Representa enfoque, contemplación e introspección.',
      keywords: ['hielo', 'enfoque', 'meditación', 'estancamiento'],
      divination: 'Necesidad de enfoque e introspección.',
    },
    jera: {
      name: 'Jera',
      meaning: 'Significa "año", "cosecha" y "recompensa". Simboliza esfuerzo y paciencia para buenos resultados.',
      symbolism: 'Representa ciclos estacionales y vivir al ritmo de la naturaleza.',
      keywords: ['cosecha', 'esfuerzo', 'paciencia', 'recompensa'],
      divination: 'Los frutos del esfuerzo y el ciclo natural.',
    },
    eihwaz: {
      name: 'Eihwaz',
      meaning: 'Significa "tejo", "muerte y renacimiento" y "cambio". Simboliza transformación y renovación.',
      symbolism: 'Representa cambio, renacimiento y crecimiento espiritual.',
      keywords: ['cambio', 'renacimiento', 'crecimiento', 'espiritualidad'],
      divination: 'Crecimiento espiritual a través de la transformación.',
    },
    perthro: {
      name: 'Perthro',
      meaning: 'Significa "destino", "misterio" y "lo oculto". Simboliza destino y secretos.',
      symbolism: 'Representa destino, secretos y conocimiento oculto.',
      keywords: ['destino', 'secreto', 'misterio', 'conocimiento'],
      divination: 'Conocimiento oculto y fuerza del destino.',
    },
    algiz: {
      name: 'Algiz',
      meaning: 'Significa "defensa", "protección" y "conexión". Simboliza protección divina.',
      symbolism: 'Representa protección, conexión sagrada y despertar espiritual.',
      keywords: ['protección', 'conexión', 'despertar', 'sagrado'],
      divination: 'Protección divina y despertar espiritual.',
    },
    sowilo: {
      name: 'Sowilo',
      meaning: 'Significa "sol", "victoria" y "éxito". Simboliza triunfo y logro.',
      symbolism: 'Representa éxito, victoria, vitalidad y luz.',
      keywords: ['sol', 'victoria', 'éxito', 'vitalidad'],
      divination: 'Confianza en el éxito y la victoria.',
    },
    tiwaz: {
      name: 'Tiwaz',
      meaning: 'Significa "el dios Tyr", "guerra" y "justicia". Simboliza justicia y sacrificio.',
      symbolism: 'Representa justicia, sacrificio, valentía y liderazgo.',
      keywords: ['justicia', 'sacrificio', 'valentía', 'liderazgo'],
      divination: 'Valentía y sacrificio justo.',
    },
    berkanan: {
      name: 'Berkanan',
      meaning: 'Significa "abedul", "crecimiento" y "nuevo comienzo". Simboliza desarrollo y renovación.',
      symbolism: 'Representa crecimiento, renacimiento, feminidad y nacimiento.',
      keywords: ['crecimiento', 'renacimiento', 'nuevo comienzo', 'fertilidad'],
      divination: 'Oportunidad de nuevos comienzos y crecimiento.',
    },
    ehwaz: {
      name: 'Ehwaz',
      meaning: 'Significa "caballo", "asociación" y "confianza". Simboliza cooperación y lealtad.',
      symbolism: 'Representa asociación, confianza, cooperación y lealtad.',
      keywords: ['asociación', 'confianza', 'cooperación', 'lealtad'],
      divination: 'Una asociación confiable basada en la confianza.',
    },
    mannaz: {
      name: 'Mannaz',
      meaning: 'Significa "humano", "comunidad" e "interdependencia". Simboliza humanidad y sociedad.',
      symbolism: 'Representa humanidad, comunidad, interdependencia y sabiduría.',
      keywords: ['humanidad', 'comunidad', 'sabiduría', 'interdependencia'],
      divination: 'Sabiduría humana y espíritu comunitario.',
    },
    laguz: {
      name: 'Laguz',
      meaning: 'Significa "agua", "flujo" e "intuición". Simboliza intuición y emoción.',
      symbolism: 'Representa intuición, emoción, flujo y cambio.',
      keywords: ['agua', 'intuición', 'emoción', 'flujo'],
      divination: 'La importancia de seguir la intuición.',
    },
    ingwaz: {
      name: 'Ingwaz',
      meaning: 'Significa "el dios Ing", "fertilidad" y "finalización". Simboliza plenitud y prosperidad.',
      symbolism: 'Representa finalización, prosperidad y crecimiento interior.',
      keywords: ['finalización', 'prosperidad', 'crecimiento', 'fuerza interior'],
      divination: 'Etapa de finalización y maduración interior.',
    },
    dagaz: {
      name: 'Dagaz',
      meaning: 'Significa "día", "despertar" y "comprensión". Simboliza claridad y cambio.',
      symbolism: 'Representa comprensión, despertar, equilibrio y transformación.',
      keywords: ['comprensión', 'despertar', 'equilibrio', 'cambio'],
      divination: 'Inicio de una nueva perspectiva y conciencia.',
    },
    othalan: {
      name: 'Othalan',
      meaning: 'Significa "herencia", "tierra ancestral" y "legado". Simboliza familia, tradición y raíces.',
      symbolism: 'Representa linaje, tradición y sabiduría heredada de los antepasados.',
      keywords: ['herencia', 'tradición', 'familia', 'raíces'],
      divination: 'Sabiduría ancestral y tradición familiar.',
    },
  },

  fr: {
    fehu: {
      name: 'Fehu',
      meaning: 'Signifie « bétail », « richesse » et « propriété ». Il symbolise l\'abondance matérielle et la réussite.',
      symbolism: 'Représente les fruits du travail, la créativité et les nouveaux départs.',
      keywords: ['richesse', 'réussite', 'abondance', 'énergie'],
      divination: 'Signe de réussite matérielle et de nouvelles opportunités.',
    },
    uruz: {
      name: 'Uruz',
      meaning: 'Signifie « aurochs », « force » et « vitalité ». Il symbolise la puissance primordiale et l\'énergie vitale.',
      symbolism: 'Représente la force intérieure, le courage et la puissance brute de la nature.',
      keywords: ['force', 'courage', 'vitalité', 'changement'],
      divination: 'Manifestation d\'une forte volonté et d\'une grande vitalité.',
    },
    thurisaz: {
      name: 'Thurisaz',
      meaning: 'Signifie « géant », « épine » et « marteau de Thor ». Il symbolise la protection et la défense.',
      symbolism: 'Représente une défense active, la protection et une puissance redoutable.',
      keywords: ['protection', 'défense', 'puissance', 'défi'],
      divination: 'Protection contre le danger et détermination inébranlable.',
    },
    ansuz: {
      name: 'Ansuz',
      meaning: 'Signifie « dieu », « Odin » et « sagesse ». Il symbolise la sagesse divine et l\'inspiration.',
      symbolism: 'Représente la communication, la sagesse, l\'inspiration et les messages sacrés.',
      keywords: ['sagesse', 'communication', 'inspiration', 'sacré'],
      divination: 'Transmission de sagesse divine et d\'inspiration.',
    },
    raidho: {
      name: 'Raidho',
      meaning: 'Signifie « voyage », « chevauchée » et « mouvement ». Il symbolise la route et le changement.',
      symbolism: 'Représente le voyage de la vie, le progrès et le rythme.',
      keywords: ['voyage', 'changement', 'progrès', 'rythme'],
      divination: 'La bonne direction et le bon chemin.',
    },
    kaunan: {
      name: 'Kaunan',
      meaning: 'Signifie « torche », « lumière » et « connaissance ». Il symbolise l\'apprentissage et l\'éveil.',
      symbolism: 'Représente la créativité, l\'art, le savoir-faire et la transformation.',
      keywords: ['connaissance', 'création', 'art', 'changement'],
      divination: 'Force créatrice et acquisition de nouvelles connaissances.',
    },
    gebo: {
      name: 'Gebo',
      meaning: 'Signifie « cadeau », « échange » et « équilibre ». Il symbolise la réciprocité et l\'harmonie.',
      symbolism: 'Représente les relations, le partenariat, l\'équilibre et la réciprocité.',
      keywords: ['cadeau', 'échange', 'équilibre', 'relation'],
      divination: 'Une relation équilibrée et un respect mutuel.',
    },
    wunjo: {
      name: 'Wunjo',
      meaning: 'Signifie « joie », « bonheur » et « harmonie ». Il symbolise l\'accomplissement et la satisfaction.',
      symbolism: 'Représente la paix intérieure, la satisfaction et l\'équilibre de vie.',
      keywords: ['joie', 'bonheur', 'harmonie', 'satisfaction'],
      divination: 'Atteindre le bonheur et la paix intérieure.',
    },
    hagalaz: {
      name: 'Hagalaz',
      meaning: 'Signifie « grêle », « destruction » et « épreuve ». Il symbolise les épreuves et la transformation.',
      symbolism: 'Représente les épreuves, les changements brusques et les nouveaux départs.',
      keywords: ['épreuve', 'destruction', 'changement', 'renouveau'],
      divination: 'Croissance par l\'épreuve et la transformation.',
    },
    nauthiz: {
      name: 'Nauthiz',
      meaning: 'Signifie « besoin », « pénurie » et « contrainte ». Il symbolise la nécessité et le désir.',
      symbolism: 'Représente l\'endurance, les limites, l\'apprentissage et la croissance.',
      keywords: ['besoin', 'endurance', 'contrainte', 'apprentissage'],
      divination: 'Sagesse acquise par la patience et l\'endurance.',
    },
    isaz: {
      name: 'Isaz',
      meaning: 'Signifie « glace », « immobilité » et « concentration ». Il symbolise la concentration et la méditation.',
      symbolism: 'Représente la concentration, la contemplation et l\'introspection.',
      keywords: ['glace', 'concentration', 'méditation', 'immobilité'],
      divination: 'Besoin de concentration et d\'introspection.',
    },
    jera: {
      name: 'Jera',
      meaning: 'Signifie « année », « récolte » et « récompense ». Il symbolise l\'effort et la patience pour de bons résultats.',
      symbolism: 'Représente les cycles saisonniers et la vie au rythme de la nature.',
      keywords: ['récolte', 'effort', 'patience', 'récompense'],
      divination: 'Les fruits de l\'effort et le cycle naturel.',
    },
    eihwaz: {
      name: 'Eihwaz',
      meaning: 'Signifie « if », « mort et renaissance » et « changement ». Il symbolise la transformation et le renouveau.',
      symbolism: 'Représente le changement, la renaissance et la croissance spirituelle.',
      keywords: ['changement', 'renaissance', 'croissance', 'spiritualité'],
      divination: 'Croissance spirituelle à travers la transformation.',
    },
    perthro: {
      name: 'Perthro',
      meaning: 'Signifie « destin », « mystère » et « caché ». Il symbolise le destin et les secrets.',
      symbolism: 'Représente le destin, les secrets et le savoir caché.',
      keywords: ['destin', 'secret', 'mystère', 'connaissance'],
      divination: 'Savoir caché et puissance du destin.',
    },
    algiz: {
      name: 'Algiz',
      meaning: 'Signifie « défense », « protection » et « lien ». Il symbolise la protection divine.',
      symbolism: 'Représente la protection, le lien sacré et l\'éveil spirituel.',
      keywords: ['protection', 'lien', 'éveil', 'sacré'],
      divination: 'Protection divine et éveil spirituel.',
    },
    sowilo: {
      name: 'Sowilo',
      meaning: 'Signifie « soleil », « victoire » et « réussite ». Il symbolise le triomphe et l\'accomplissement.',
      symbolism: 'Représente la réussite, la victoire, la vitalité et la lumière.',
      keywords: ['soleil', 'victoire', 'réussite', 'vitalité'],
      divination: 'Confiance dans la réussite et la victoire.',
    },
    tiwaz: {
      name: 'Tiwaz',
      meaning: 'Signifie « le dieu Tyr », « guerre » et « justice ». Il symbolise la justice et le sacrifice.',
      symbolism: 'Représente la justice, le sacrifice, le courage et le leadership.',
      keywords: ['justice', 'sacrifice', 'courage', 'leadership'],
      divination: 'Courage et sacrifice juste.',
    },
    berkanan: {
      name: 'Berkanan',
      meaning: 'Signifie « bouleau », « croissance » et « nouveau départ ». Il symbolise le développement et le renouveau.',
      symbolism: 'Représente la croissance, la renaissance, la féminité et la naissance.',
      keywords: ['croissance', 'renaissance', 'nouveau départ', 'fécondité'],
      divination: 'Une chance de nouveau départ et de croissance.',
    },
    ehwaz: {
      name: 'Ehwaz',
      meaning: 'Signifie « cheval », « partenariat » et « confiance ». Il symbolise la coopération et la loyauté.',
      symbolism: 'Représente le partenariat, la confiance, la coopération et la loyauté.',
      keywords: ['partenariat', 'confiance', 'coopération', 'loyauté'],
      divination: 'Un partenariat fiable fondé sur la confiance.',
    },
    mannaz: {
      name: 'Mannaz',
      meaning: 'Signifie « humain », « communauté » et « interdépendance ». Il symbolise l\'humanité et la société.',
      symbolism: 'Représente l\'humanité, la communauté, l\'interdépendance et la sagesse.',
      keywords: ['humanité', 'communauté', 'sagesse', 'interdépendance'],
      divination: 'Sagesse humaine et esprit communautaire.',
    },
    laguz: {
      name: 'Laguz',
      meaning: 'Signifie « eau », « flux » et « intuition ». Il symbolise l\'intuition et l\'émotion.',
      symbolism: 'Représente l\'intuition, l\'émotion, le flux et le changement.',
      keywords: ['eau', 'intuition', 'émotion', 'flux'],
      divination: 'L\'importance de suivre son intuition.',
    },
    ingwaz: {
      name: 'Ingwaz',
      meaning: 'Signifie « le dieu Ing », « fertilité » et « accomplissement ». Il symbolise la plénitude et la prospérité.',
      symbolism: 'Représente l\'accomplissement, la prospérité et la croissance intérieure.',
      keywords: ['accomplissement', 'prospérité', 'croissance', 'force intérieure'],
      divination: 'Phase d\'accomplissement et de maturation intérieure.',
    },
    dagaz: {
      name: 'Dagaz',
      meaning: 'Signifie « jour », « éveil » et « compréhension ». Il symbolise la clarté et le changement.',
      symbolism: 'Représente la compréhension, l\'éveil, l\'équilibre et la transformation.',
      keywords: ['compréhension', 'éveil', 'équilibre', 'changement'],
      divination: 'Début d\'une nouvelle conscience et perspective.',
    },
    othalan: {
      name: 'Othalan',
      meaning: 'Signifie « héritage », « terre ancestrale » et « legs ». Il symbolise la famille, la tradition et les racines.',
      symbolism: 'Représente la lignée, la tradition et la sagesse transmise par les ancêtres.',
      keywords: ['héritage', 'tradition', 'famille', 'racines'],
      divination: 'Sagesse ancestrale et tradition familiale.',
    },
  },
};
